<a href="https://colab.research.google.com/github/ABHAY1937/NLP/blob/main/Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
!pip install --upgrade pip


In [35]:
!pip install tensorflow-gpu==2.8.0



In [36]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [37]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [38]:
### sentences
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [39]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [40]:
### Vocabulary size
voc_size=10000

OneHot Representation


In [41]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[401, 4580, 9543, 3549, 9980, 8794], [374, 1295, 9543, 5694, 4277, 4275], [9330, 6189, 8426, 3209], [401, 3774, 9543, 2884, 401, 2510], [5419, 3914, 1606, 9543, 5694, 4277, 4275], [6183, 9543, 5694, 4277, 764, 1823]]


Word Embedding Represntation

In [42]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [43]:
import numpy as np

In [44]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0  401 4580 9543 3549 9980 8794]
 [   0    0  374 1295 9543 5694 4277 4275]
 [   0    0    0    0 9330 6189 8426 3209]
 [   0    0  401 3774 9543 2884  401 2510]
 [   0 5419 3914 1606 9543 5694 4277 4275]
 [   0    0 6183 9543 5694 4277  764 1823]]


In [45]:
## 10 feature dimesnions
dim=10


In [46]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [47]:
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [48]:
##'the glass of milk',
embedded_docs[0]

array([   0,    0,  401, 4580, 9543, 3549, 9980, 8794], dtype=int32)

In [49]:
model.predict(embedded_docs[0])

array([[-0.03331278, -0.01101623, -0.03369079, -0.00125539,  0.02685292,
         0.00742054, -0.0262111 , -0.00229708,  0.04183099, -0.02937368],
       [-0.03331278, -0.01101623, -0.03369079, -0.00125539,  0.02685292,
         0.00742054, -0.0262111 , -0.00229708,  0.04183099, -0.02937368],
       [ 0.01490707,  0.03626745, -0.02485825,  0.02047315, -0.03666893,
        -0.02434584,  0.04507682, -0.0199718 ,  0.03674184,  0.00505622],
       [-0.01231179, -0.02204208,  0.03950112, -0.03765894,  0.01244458,
         0.04184606, -0.00303229, -0.01288253,  0.01934591,  0.0281488 ],
       [-0.01630976,  0.01408777, -0.01303919, -0.00301235, -0.04118482,
         0.00087114,  0.02917184, -0.01311021,  0.02278696,  0.03236772],
       [ 0.01476738, -0.02687821, -0.0316964 ,  0.01802344,  0.01975515,
        -0.03539356, -0.04109387,  0.00286412,  0.02102145, -0.04650904],
       [ 0.01077255,  0.01353072, -0.00010274,  0.03393238, -0.02499614,
        -0.00667731,  0.03947398, -0.00435785

In [50]:
print(model.predict(embedded_docs))

[[[-0.03331278 -0.01101623 -0.03369079 -0.00125539  0.02685292
    0.00742054 -0.0262111  -0.00229708  0.04183099 -0.02937368]
  [-0.03331278 -0.01101623 -0.03369079 -0.00125539  0.02685292
    0.00742054 -0.0262111  -0.00229708  0.04183099 -0.02937368]
  [ 0.01490707  0.03626745 -0.02485825  0.02047315 -0.03666893
   -0.02434584  0.04507682 -0.0199718   0.03674184  0.00505622]
  [-0.01231179 -0.02204208  0.03950112 -0.03765894  0.01244458
    0.04184606 -0.00303229 -0.01288253  0.01934591  0.0281488 ]
  [-0.01630976  0.01408777 -0.01303919 -0.00301235 -0.04118482
    0.00087114  0.02917184 -0.01311021  0.02278696  0.03236772]
  [ 0.01476738 -0.02687821 -0.0316964   0.01802344  0.01975515
   -0.03539356 -0.04109387  0.00286412  0.02102145 -0.04650904]
  [ 0.01077255  0.01353072 -0.00010274  0.03393238 -0.02499614
   -0.00667731  0.03947398 -0.00435785  0.02573283 -0.02163684]
  [ 0.00053187 -0.03723139  0.0094403  -0.0460665   0.00979824
    0.0196096   0.0231461  -0.00644307  0.045385

In [51]:
embedded_docs[0]

array([   0,    0,  401, 4580, 9543, 3549, 9980, 8794], dtype=int32)

In [52]:
print(model.predict(embedded_docs)[0])

[[-0.03331278 -0.01101623 -0.03369079 -0.00125539  0.02685292  0.00742054
  -0.0262111  -0.00229708  0.04183099 -0.02937368]
 [-0.03331278 -0.01101623 -0.03369079 -0.00125539  0.02685292  0.00742054
  -0.0262111  -0.00229708  0.04183099 -0.02937368]
 [ 0.01490707  0.03626745 -0.02485825  0.02047315 -0.03666893 -0.02434584
   0.04507682 -0.0199718   0.03674184  0.00505622]
 [-0.01231179 -0.02204208  0.03950112 -0.03765894  0.01244458  0.04184606
  -0.00303229 -0.01288253  0.01934591  0.0281488 ]
 [-0.01630976  0.01408777 -0.01303919 -0.00301235 -0.04118482  0.00087114
   0.02917184 -0.01311021  0.02278696  0.03236772]
 [ 0.01476738 -0.02687821 -0.0316964   0.01802344  0.01975515 -0.03539356
  -0.04109387  0.00286412  0.02102145 -0.04650904]
 [ 0.01077255  0.01353072 -0.00010274  0.03393238 -0.02499614 -0.00667731
   0.03947398 -0.00435785  0.02573283 -0.02163684]
 [ 0.00053187 -0.03723139  0.0094403  -0.0460665   0.00979824  0.0196096
   0.0231461  -0.00644307  0.04538511 -0.045735  ]]
